echo "arguments total: $#"
echo "scripts name: $0"
echo "script 1st argument: $1"
echo "script 2nd argument: $2"
echo "script 3rd argument: $3"
echo "list of all argument: * $*"
echo "list of all argument: @ $@"
echo "PID of shell: $$"
